### ISSUE TITLE
light theme?

### ISSUE THREAD

**Issue by anarcat** [srcery-colors/.github#3]
I moved to srcery from Solarized and I am mostly happy with my decision: great theme, great contrast, I love the colors, and it mostly works on all my applications. It's awesome!

One thing I *am* missing from Solarized is a "light" theme version for when I bring my laptop in plain daylight. Right now my compromise is to just switch to solarized-light but I'd love to keep similar contrast and colors... is that something that has ever been considered?

Obviously, feel free to immediately close this issue, I just wanted to at least make sure this was a deliberate decision and not just some TODO item lost in someone's head. ;)

**Comment by roosta** [comment]
I've thought about it, I did away with light theme when I initially made srcery, because I never use light mode myself. I never really designed the palette to work in light mode,but it might work, with some adjustments.

I'll do some experiments and see if it is even doable.

**Comment by roosta** [comment]
I did some initial tests, and outlook isn't good. I'd have to basically create a new palette based of the dark one. Its a fair bit of work, so sorry to disappoint...there might be a light mode in the future but I can say for sure when.

**Comment by roosta** [comment]
Thanks for understanding :) I suppose I'd recommend gruvbox's light variant, it is after all the main theme that inspired Srcery, and they both share a fair bit of color language (green used for strings for example)

I'll be sure to let you know of any progress on light theme in the future.
